### PR TITLE
"Fix" macro name conflicts.

### PR DESCRIPTION
**Pull request by rtohid**
This is a frail fix, making sure Halide is included before HPX.

### CODE REVIEW

**Comment by hkaiser** [comment]
What macro name conflicts is this fixing?

**Comment by rtohid** [comment]
There is a log list of ELF binding symbols found in: https://github.com/halide/Halide/blob/master/src/Elf.h

**Comment by hkaiser** [comment]
> There is a log list of ELF binding symbols found in: https://github.com/halide/Halide/blob/master/src/Elf.h

Hmmm, that file does not define any macros :/ What macro names are conflicting?

**Comment by rtohid** [comment]
My mistake, symbol names found here: https://github.com/halide/Halide/blob/085e11e0dc40591bdbb742f8b4df6130b299bc9b/src/Elf.h#L52

**Comment by hkaiser** [comment]
> My mistake, symbol names found here: https://github.com/halide/Halide/blob/085e11e0dc40591bdbb742f8b4df6130b299bc9b/src/Elf.h#L52

Does it still work if you `#include <hpx/config.hpp>`  first? On Windows HPX headers have to be included first to avoid a lot of warnings.

**Comment by rtohid** [comment]
Yes, it still works if `hpx/config.hpp` is included before `Halide.h`.

**Comment by hkaiser** [comment]
> Yes, it still works if `hpx/config.hpp` is included before `Halide.h`.

Thanks, would you mind changing this PR accordingly?

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
